### ISSUE TITLE
cannot work with latest  Locale-Emulator v2.5.0.1

### ISSUE THREAD

**Issue by henry1989zhang** [Svintooo/LEShortcutCreator#1] opened 2021-12-22 07:04 UTC
https://github.com/xupefei/Locale-Emulator

Hi,  your shortcutCreator  didn't work with Locale-Emulator v2.5.0.1

can enhance it ?

thanks

**Comment by Svintooo** [comment] 2021-12-22 07:26
Hi!

What exactly didn't work? A step-by-step guide on how to reproduce the error would be great.

I used LEShortcutCreator yesterday with latest Locale-Emulator and I didn't notice any problems at the time.

**Comment by Svintooo** [comment] 2022-03-26 00:21
I played around with Locale Emulator a little on Win11 and found that it didn't work if Locale Emulator (LE) have not generated its config file. I made a small update to fix this.

In conclusion: If the list of languages is empty, you can now fix this problem by clicking the "Edit List" button.
This will start the LE GUI window. Just close it. The default languages should now be avilable.

I am not sure if this is the error you experienced, but I hpe this makes it easier to use my LEShortcutCreator.

**Comment by Svintooo** [comment] 2022-04-03 21:22
Hi again!

I found another error where LE Shortcut Creator didn't work with Locale-Emulator.
If running from the same folder, then Locale-Emulator must have LEInstall.exe run at least once (even if not installing Locale-Emulator).

Info has also been added to bottom of README.

I will now close this issue since I haven't heard from you for a while. But feel free to open it again if you still have problems.

**Closed as completed by Svintooo** 2022-04-03 21:22 UTC
